### ISSUE TITLE
problem while running tutorial

### ISSUE THREAD

**Issue by dvot197007** [bailaohe/parade#13]
Hello,
After installing parade, I tried to follow your tutorial and got the following error message:

(modelling) C:\DOT\2_Coding\m_Python\PyMMS\Parade_ETL\example>parade task create movie_data -t etl
Traceback (most recent call last):
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ndot2\Miniconda3\envs\modelling\Scripts\parade.exe\__main__.py", line 9, in <module>
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\cmdline.py", line 73, in execute
    context = Context(bootstrap)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\context.py", line 36, in __init__
    self._init_configstore()
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\context.py", line 133, in _init_configstore
    self._configstore = self._load_plugin('config', ConfigStore)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\context.py", line 145, in _load_plugin
    plugin_cls = get_class(driver, plugin_class, 'parade.' + plugin_token, self.name + '.contrib.' + plugin_token)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\utils\modutils.py", line 78, in get_class
    for cls in iter_classes(base_class, *modules, class_filter=lambda x: x.__module__.split('.')[-1] == name):
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\utils\modutils.py", line 63, in iter_classes
    for module in walk_modules(root_module):
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\utils\modutils.py", line 49, in walk_modules
    submod = import_module(fullpath)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\config\consul.py", line 1, in <module>
    import consul
ModuleNotFoundError: No module named 'consul'

Regards,
David

**Comment by dvot197007** [comment]
pip installing python-consul seems to have fixed the problem
