### ISSUE TITLE
Another problem when running tutorial

### ISSUE THREAD

**Issue by dvot197007** [bailaohe/parade#14]
Hello,
I got this error message when running the tutorial:

(modelling) C:\DOT\2_Coding\m_Python\PyMMS\Parade_ETL\example>parade task exec movie_data
2018-04-13 18:12:30,695 Parade       INFO     single task movie_data provided, ignore its dependencies
2018-04-13 18:12:30,695 Parade       INFO     Temporary flow [example] created!
Traceback (most recent call last):
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ndot2\Miniconda3\envs\modelling\Scripts\parade.exe\__main__.py", line 9, in <module>
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\cmdline.py", line 75, in execute
    return command.run(context, **command_args)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\command\__init__.py", line 48, in run
    return self.run_internal(context, **kwargs)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\command\task\run.py", line 24, in run_internal
    return engine.execute_async(tasks=tasks, force=force, nodep=nodep)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\engine.py", line 86, in execute_async
    return self._execute_flow(flow, new_thread=new_thread, force=force)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\engine.py", line 89, in _execute_flow
    flow_id = self.context.on_flow_start(flow)
  File "c:\users\ndot2\miniconda3\envs\modelling\lib\site-packages\parade\core\context.py", line 172, in on_flow_start
    self.sys_recorder.init_record_tables()
AttributeError: 'NoneType' object has no attribute 'init_record_tables'

**Comment by bailaohe** [comment]
Sorry for late response. The reason for your issue is lack of configuration "checkpoint.connection" in your ymal config file. check this:

[https://github.com/bailaohe/parade/blob/master/src/parade/core/context.py#L159](url)

I've add this missing default config in the template.
